name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 2.7
            toxenv: py27
          - python-version: 3.5
            toxenv: py3.5
          - python-version: 3.6
            toxenv: py3.6
          - python-version: 3.7
            toxenv: py3.7
          - python-version: 3.8
            toxenv: py3.8      
          - python-version: 3.9
            toxenv: py3.9
          - python-version: pypy
            toxenv: pypy
          - python-version: pypy3
            toxenv: pypy3   

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Tox
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
